#!/usr/bin/env python3
"""Writes kitty's current-theme.conf from a JSON payload of
{background, foreground, cursor, colors: [16 hex strings]}.

A small argv-based helper (not inline shell) so color data never needs
escaping through QML/shell string interpolation — the exact kind of
mistake that overwrote the user's hand-tuned kitty theme earlier in this
project's history with no way back. Mirrors the real, hand-fixed
~/.config/kitty/themes/T480.conf field layout exactly.

Usage: kitty_write_theme.py <input.json> <output conf path>
"""
import json
import sys


def main():
    if len(sys.argv) != 3:
        print("usage: kitty_write_theme.py <input.json> <output path>", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1]) as f:
        theme = json.load(f)

    colors = theme["colors"]
    if len(colors) != 16:
        print(f"error: expected 16 colors, got {len(colors)}", file=sys.stderr)
        sys.exit(1)

    lines = [
        "# Auto-generated by kitty_write_theme.py from the Theme panel's carousel.",
        f"background            {theme['background']}",
        f"foreground             {theme['foreground']}",
        f"cursor                  {theme['cursor']}",
        "",
        "# --- ANSI Colors ---",
    ]
    for i, hexval in enumerate(colors):
        lines.append(f"color{i}  {hexval}")

    with open(sys.argv[2], "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
